[package]
name = "hakarl"
version = "0.1.0"
authors = ["Hugo Kapp <hugo.kapp@epfl.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.1.1"
rand = "0.7.3"
atomic-option = "0.1.2"
